### ISSUE TITLE
`prepend_bos` inconsistency

### ISSUE THREAD

**Issue by joelburget** [neelnanda-io/Easy-Transformer#74]
Yesterday @epurdy and I were working on an implementation of causal tracing from ROME. We ended up getting stuck for a while because when we ran the model it unexpectedly prepended a BOS token (in contrast to running the tokenizer by itself or with `model.to_str_tokens`, which doesn't). Looking through the codebase I noticed that of the six functions with a `prepend_bos` option, they're evenly split on the default. I think these defaults make sense in isolation but may be confusing when used together. Not sure what the right fix is here (or if it needs to be changed at all) but thought I'd at least raise this for discussion.

https://github.com/neelnanda-io/Easy-Transformer/blob/e5790469df3ebe26547c2016f899389e9f7bec30/easy_transformer/EasyTransformer.py#L146

https://github.com/neelnanda-io/Easy-Transformer/blob/e5790469df3ebe26547c2016f899389e9f7bec30/easy_transformer/EasyTransformer.py#L299

https://github.com/neelnanda-io/Easy-Transformer/blob/e5790469df3ebe26547c2016f899389e9f7bec30/easy_transformer/EasyTransformer.py#L345

https://github.com/neelnanda-io/Easy-Transformer/blob/e5790469df3ebe26547c2016f899389e9f7bec30/easy_transformer/EasyTransformer.py#L395

https://github.com/neelnanda-io/Easy-Transformer/blob/e5790469df3ebe26547c2016f899389e9f7bec30/easy_transformer/EasyTransformer.py#L935

https://github.com/neelnanda-io/Easy-Transformer/blob/e5790469df3ebe26547c2016f899389e9f7bec30/easy_transformer/utils.py#L440

**Comment by neelnanda-io** [comment]
Thanks for flagging! You guys being stuck for a while is useful data (and sorry about that!).

I've gone back and forth about the right way to do this. So, roughly, here's my reasoning:
* Some models are trained with a BOS token (OPT and all of my models) and will completely break without this at the start of the input)
* SOme models were not trained with a BOS token (GPT-2 and probs GPT-Neo) but in practice tend to treat the first token weirdly and empirically prepending BOS makes them work better. Eg "John and Mary went to the store..." will tend to get much worse results on the IOI task than "<BOS>John and Mary went to the store..." or "After John and Mary went to the store..."
* I would like the default to be that all *inputs* to the model have BOS prepended
* I would like the default that when the user is analysing any *substring* BOS is not prepended

My roughly intended usage is that people use to_tokens and to_str_tokens when manually playing around and analysing and understanding strings, and more often analysing substrings than inputs, but probably both. So the manually playing around functions do not prepend BOS by default, but the "actually input to a model" functions do.

But I agree this is confusing and could totally change my mind on this!

**Comment by neelnanda-io** [comment]
(I've had complaints about the other way round, and a bunch of people screwed up in the application task bc it automatically prepended BOS to the answers lol)

**Comment by neelnanda-io** [comment]
Any takes for what would have felt intuitive to you/what could be changed to make this easy to debug? Eg, what places did you look first when confused?

Possible ideas:
* When someone inputs a string to forwards, print/log.info "automatically prepended BOS"
* Have a FAQ that explains this (under a Q like "the model's outputs have a different length to when I do model.to_tokens on the input text")
* Better document this in the doc strings of the various tokenization functions (I'll document it in the new demo notebook whenever I get round to writing that...)

**Comment by joelburget** [comment]
I think all of your suggestions are great!

Looking through all of the functions, I don't think `test_prompt` matters too much, since it just prints output without returning anything, and nothing calls it, so I'll ignore it. However, is this a bug? (`prepend_bos=False` should be `prepend_bos=prepend_bos`?)

https://github.com/neelnanda-io/Easy-Transformer/blob/e5790469df3ebe26547c2016f899389e9f7bec30/easy_transformer/utils.py#L453-L455

---

Focusing on the other five functions (which, according to me, matter). One thing which makes me a bit uncomfortable: `forward`, `to_str_tokens`, `get_token_position`, and `generate` all use the `prepend_bos` argument only when their input is a string (ignoring it for tensors). Only `to_tokens` consistently applies the BOS token in both cases. I understand why, but still, this could be confusing.

As for what the default should be, one idea is to change the default to be `None` everywhere. When `prepend_bos is None`, do the appropriate thing for the given model.

A natural extension would be to add `prepend_bos` to `EasyTransformerConfig` (with different defaults depending on the model you use). Now, when `prepend_bos is None`, defer to the config setting.

Another option: if `to_str_tokens` returns an unexpected BOS token, it's really easy to see / debug. It's slightly harder but still relatively easy to tell in `to_tokens` and `get_token_position`. This nudges me a bit in the direction of setting the default to be `prepend_bos=True` for these cases (if we don't use my other suggestion), since it'll take about five seconds to update your code if you see a BOS token you didn't expect. It just so happens that by changing those three defaults, every function would now (consistently) have `prepend_bos=True`.

**Comment by neelnanda-io** [comment]
> However, is this a bug? (prepend_bos=False should be prepend_bos=prepend_bos?)

No, that's intentional - you only prepend BOS to the start of an input, answer is a substring so you never prepend_bos

**Comment by neelnanda-io** [comment]
> Only to_tokens consistently applies the BOS token in both cases

I don't think this is true - it applies BOS to strings and lists of strings but not to tensors. I *think* the other functions also work like that

**Comment by joelburget** [comment]
> what places did you look first when confused?

Eric had suggested it was something like an off-by-one error and had the idea to add "<|endoftext|>" to the beginning of our string. We could see that the string tokens looked reasonable before and after this change but the issue wasn't fixed. At this point we had been working for a couple hours so we called it a day. Later I came back and started printing tensor shapes. I happened to notice that the position dimension was something like 7 instead of 6, which lead me down the path of reading the code and noticing `prepend_bos=True` in `forward`.

**Comment by neelnanda-io** [comment]
> As for what the default should be, one idea is to change the default to be None everywhere. When prepend_bos is None, do the appropriate thing for the given model.

Part of the messiness here is that I *want* GPT-2 to default to having a BOS prepended even though it wasn't trained like that. The goal is to have the library be user friendly to a novice user, and I think that "the first token is treated weirdly and prompts where the first token is important will often break" is unexpected and confusing behaviour.

So to my eyes the core issue is substrings vs inputs

**Comment by neelnanda-io** [comment]
And thanks for the data on the experience! Sounds pretty bad (also lol, I did not plan for people to manually add <endoftext>! Possibly I should explicitly check whether that's already there?)

**Comment by neelnanda-io** [comment]
OK, I feel pretty convinced by your final suggestion of just defaulting to prepend_bos = True everywhere is most elegant, at the cost of the user needing to explicitly set this to not happen when playing with substrings. Thanks a lot for the detailed feedback!

**Comment by joelburget** [comment]
> the core issue is substrings vs inputs

Agreed. It's really a shame we use the same type for both... In Haskell or OCaml we'd just use a `newtype` / different type. I know Python has [`NewType`](https://docs.python.org/3/library/typing.html#newtype) but that maybe feels like overkill here.
